### ISSUE TITLE
Notification of a new job

### ISSUE THREAD

**Issue by haroldboom** [calr0x/OT-NodeWatch#2]
Hi, would it be possible to add a notification for a new offer being accepted? Thanks for your work mate!

**Comment by calr0x** [comment]
Absolutely. I'll knock it out asap!

**Comment by haroldboom** [comment]
Modified the bid_check.sh to look for new accepted offers. Let me know what you think


[accept_check.txt](https://github.com/calr0x/OT-NodeWatch/files/6643218/accept_check.txt)

**Comment by calr0x** [comment]
`BIDS=$(docker logs --since $INTERVAL otnode | grep "I've been chosen" | wc -l)
echo $BIDS`

1. In "I've" the apostrophe needs to be escaped like this "I\\'ve" so that the apostrophe is interpreted as just an apostrophe as it has other uses in the command line. The slash means "ignore this symbols use in Linux and just treat as an apostrophe.

2. Checking every hour will mean there is a good chance more than 1 job will be gotten in that time. Instead of telling the user how many minutes it's been since the last check in the telegram message, maybe we should tell them how many jobs were won?

The command above does this:
- Scroll thru docker logs from the last X minutes and look for "I\'ve been chosen" and count how many lines that it appears there are (the count is how we know how many jobs we got).

- Take that count and put it into $BIDS.

So maybe we say something like:

`if $BIDS -eq 1 then message to telegram "1 new offer accepted!"` (-eq means equals)
`if $BIDS -ge 2 then message to telegram "$BIDS new offers accepted!"`

What do ya think?

**Comment by haroldboom** [comment]
Genius mate I love it! That's a great idea with the number of offers, I don't have the brain for scripting haha

**Comment by haroldboom** [comment]
No idea why but it wont work with the escape character in "I've", as soon as I remove that it runs fine. I have made the changes and attached the updated script, I tested it (set interval to 100h) and it works! 
[accept_check.txt](https://github.com/calr0x/OT-NodeWatch/files/6645006/accept_check.txt)

**Comment by calr0x** [comment]
New job notification added! In the same file as bid_check!
```
cd /root/OT-NodeWatch
git pull
```
